name: build
on:
    push:
      branches:
        - master
    schedule:
      - cron: '*/30 * * * *'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-18.04
    steps:
      name: Jekyll build
      run: jekyll build
