name: Jekyll Build
on:
  #push:
  #    branches:
  #      - master
  #  schedule:
  #    - cron: '0 * * * *'
jobs:
  build-and-publish:
    name: Build and Publish Jekyll site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: meitar/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
