name: Jekyll Build
on:
    push:
      branches:
        - master
    schedule:
      - cron: '0 * * * *'
jobs:
  hello:
    name: Greet
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Patrick'
        id: hello
      - name: Echo greeting time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
  build-and-publish:
    name: Build and Publish Jekyll site
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - uses: meitar/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
          remote_url: https://github.com/this-is-patrick/this-is-patrick.github.io
